/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */

package org.openmrs.module.amrsreport.rule;

public interface EvaluableNameConstants {

	String ADMITTED_TO_HOSPITAL = "ADMITTED TO HOSPITAL";

	String ALL = "ALL";

	String AMPHOTERICIN_B = "AMPHOTERICIN B";

	String ANTIRETROVIRAL_PLAN = "ANTIRETROVIRAL PLAN";

	String ANTIRETROVIRAL_DRUGS = "ANTIRETROVIRAL DRUGS";

	String ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String ANTIRETROVIRALS_STARTED = "ANTIRETROVIRALS STARTED";

	String CD4_COUNT = "CD4 COUNT";

	String CD4_PANEL = "CD4 PANEL";

	String CD4_PERCENT = "CD4 PERCENT";

	String CHEMISTRY_LAB_TESTS = "CHEMISTRY LAB TESTS";

	String COMPLETE_BLOOD_COUNT = "COMPLETE BLOOD COUNT";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TRANSMISSION_PROPHYLAXIS = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TRANSMISSION PROPHYLAXIS";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String CRYPTOCOCCAL_TREATMENT_PLAN = "CRYPTOCOCCAL TREATMENT PLAN";

	String CXR = "CXR";

	String CXR_CAVITARY_LESION = "CAVITARY LESION";

	String CXR_DIFFUSE_NON_MILIARY_CHANGES = "DIFFUSE NON-MILIARY CHANGES";

	String CXR_INFILTRATE = "INFILTRATE";

	String CXR_MILIARY_CHANGES = "MILIARY CHANGES";

	String CXR_PULMONARY_EFFUSION = "PULMONARY EFFUSION";

	String DID_NOT_RECIEVE_ANTENATAL_CARE_SERVICE_THIS_VISIT = "DID NOT RECIEVE ANTENATAL CARE SERVICE THIS VISIT";

	String DOSING_CHANGE = "DOSING CHANGE";

	String DRUG_RESTART = "DRUG RESTART";

	String ESTIMATED_DATE_OF_CONFINEMENT = "ESTIMATED DATE OF CONFINEMENT";

	String EXPRESS_CARE_PROGRAM = "EXPRESS CARE PROGRAM";

	String FIRST_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 1";

	String FLUCONAZOLE = "FLUCONAZOLE";

	String HEMOGLOBIN = "HEMOGLOBIN";

	String HIV_INFECTED = "HIV INFECTED";

	String HIV_RAPID_TEST_QUALITATIVE = "HIV RAPID TEST, QUALITATIVE";

	String HIV_TEST_RESULT_PREVIOUSLY = "HIV TEST RESULT PREVIOUSLY";

	String HIV_TEST_RESULT_THIS_VISIT = "HIV TEST RESULT THIS VISIT";

	String HIV_VIRAL_LOAD_QUANTITATIVE = "HIV VIRAL LOAD, QUANTITATIVE";

	String INDIRECT_COOMBS_TEST = "INDIRECT COOMB'S TEST";

	String LAST_MENSTRUAL_PERIOD_DATE = "LAST MENSTRUAL PERIOD DATE";

	String LOW_RISK_EXPRESS_CARE_PROGRAM = "LOW RISK EXPRESS CARE PROGRAM";

	String MEDICATION_ADDED = "MEDICATION ADDED";

	String MULTIDRUG_RESISTANT_TUBERCULOSIS_REGIMEN = "MULTIDRUG-RESISTANT TUBERCULOSIS REGIMEN";

	String MULTIVITAMIN = "MULTIVITAMIN";

	String NEGATIVE = "NEGATIVE";

	String NEVIRAPINE = "NEVIRAPINE";

	String NO = "NO";

	String NONE = "NONE";

	String NUMBER_OF_DOSES_ORDERED = "NUMBER OF DOSES";

	String NUMBER_OF_WEEKS_PREGNANT = "NUMBER OF WEEKS PREGNANT";

	String NUMBER_OF_WEEKS_ON_TREATMENT = "NUMBER OF WEEKS ON TREATMENT";

	String NUTRITIONAL_SUPPORT = "NUTRITIONAL SUPPORT";

	String PARTUM_ANTIRETROVIRAL_USE = "PARTUM ANTIRETROVIRAL USE";

	String PARTUM_DOSING_PERIOD = "PARTUM DOSING PERIOD";

	String PATIENT_REPORTED_CURRENT_TUBERCULOSIS_TREATMENT = "PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT";

	String PATIENT_REPORTED_PAST_ANTIRETROVIRAL_TREATMENT = "PATIENT REPORTED PAST ANTIRETROVIRAL TREATMENT";

	String PATIENT_REPORTED_PROBLEM_ADDED = "PATIENT REPORTED PROBLEM ADDED";
	
	String CONTINUE_REGIMEN="CONTINUE REGIMEN";
	
//constants for CTX startdate and stopdate
	
	String 	PCP_PROPHYLAXIS_STARTED = "PCP PROPHYLAXIS STARTED";
	
	String  REASON_PCP_PROPHYLAXIS_STOPPED="REASON PCP PROPHYLAXIS STOPPED";
	
	String 	REASON_PCP_PROPHYLAXIS_STOPPED_DETAILED="REASON PCP PROPHYLAXIS STOPPED, DETAILED";
	
	String  CURRENT_MEDICATIONS="CURRENT MEDICATIONS";
	
	String TRIMETHOPRIM_AND_SULFAMETHOXAZOLE = "TRIMETHOPRIM AND SULFAMETHOXAZOLE";
	
	String PATIENT_REPORTED_CURRENT_PCP_PROPHYLAXIS ="PATIENT REPORTED CURRENT PCP PROPHYLAXIS";
	
	String TUBERCULOSIS_TREATMENT_COMPLETED_DATE="TUBERCULOSIS TREATMENT COMPLETED DATE";
	
	String TUBERCULOSIS_DRUG_TREATMENT_START_DATE="TUBERCULOSIS DRUG TREATMENT START DATE";
	//String ENCOUNTER_FETCH_SIZE="ENCOUNTER FETCH SIZE";
	
	//String OBS_ENCOUNTER="OBS ENCOUNTER";
	
//end of constants for CTX startdate and stopdate

	String PCP_PROPHYLAXIS_PLAN = "PCP PROPHYLAXIS PLAN";

	String PEDS_WHO_CATEGORY_QUERY = "PEDS WHO CATEGORY QUERY";

	String POSITIVE = "POSITIVE";

	String PREFERRED_MODE_OF_DELIVERY = "PREFERRED MODE OF DELIVERY";

	String PRESENCE_OF_SUGAR = "PRESENCE OF SUGAR";

	String PROBLEM_ADDED = "PROBLEM ADDED";

	String PROBLEM_RESOLVED = "PROBLEM RESOLVED";

	String PYRAZINAMIDE = "PYRAZINAMIDE";

	String QUANTITY = "QUANTITY";

	String REFERRALS_ORDERED = "REFERRALS ORDERED";

	String REFERRAL_CONSULTANT = "CONSULTANT";

	String REFERRAL_MEDICAL_OFFICER = "MEDICAL OFFICER";

	String REFILLED = "REFILLED";

	String RHESUS_FACTOR = "RHESUS FACTOR";

	String RETURN_VISIT_DATE = "RETURN VISIT DATE";

	String RIFAMPICIN = "RIFAMPICIN";

	String RITONAVIR = "RITONAVIR";

	String SECOND_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 2";

	String SERUM_CREATININE = "SERUM CREATININE";

	String SERUM_ELECTROLYTES = "SERUM ELECTROLYTES";

	String SERUM_GLUTAMIC_PYRUVIC_TRANSAMINASE = "SERUM GLUTAMIC-PYRUVIC TRANSAMINASE";

	String START_DRUGS = "START DRUGS";

	String STOP_ALL = "STOP ALL";

	String TENOFOVIR = "TENOFOVIR";

	String TETANUS_BOOSTER = "TETANUS BOOSTER";

	String TETANUS_BOOSTER_COMPLETED = "TETANUS BOOSTER COMPLETED";

	String TETANUS_BOOSTER_DETAILED = "TETANUS BOOSTER, DETAILED";

	String TESTS_ORDERED = "TESTS ORDERED";

	String TUBERCULOSIS_PROPHYLAXIS_PLAN = "TUBERCULOSIS PROPHYLAXIS PLAN";

	String TUBERCULOSIS_TREATMENT_DRUGS = "TUBERCULOSIS TREATMENT DRUGS";

	String TUBERCULOSIS_TREATMENT_PLAN = "TUBERCULOSIS TREATMENT PLAN";

	String TUBERCULOSIS_DEFAULTER_REGIMEN_BY_USING_STREPTOMYCIN = "TUBERCULOSIS DEFAULTER REGIMEN BY USING STREPTOMYCIN";

	String TUBERCULOSIS_TREATMENT_STARTED = "TUBERCULOSIS TREATMENT STARTED";

	String ENCOUNTER_TYPE_ANCINITIAL = "ANCINITIAL";

	String ENCOUNTER_TYPE_ANCRETURN = "ANCRETURN";

	String ENCOUNTER_TYPE_ADULT_INITIAL = "ADULTINITIAL";

	String ENCOUNTER_TYPE_ADULT_RETURN = "ADULTRETURN";

	String ENCOUNTER_TYPE_ADULT_NONCLINICALMEDICATION = "ADULTNONCLINICALMEDICATION";

	String ENCOUNTER_TYPE_PEDIATRIC_INITIAL = "PEDSINITIAL";

	String ENCOUNTER_TYPE_PEDIATRIC_RETURN = "PEDSRETURN";

	String ENCOUNTER_TYPE_PEDIATRIC_NONCLINICALMEDICATION = "PEDSNONCLINICALMEDICATION";

	String ECSTABLE = "ECSTABLE";
	//Additional concepts for cryptococcal rule
	String ITRACONAZOLE ="ITRACONAZOLE";
	
	//Additional concepts for Entry Point rule
	String MOBILE_VOLUNTARY_COUNSELING_AND_TESTING = "MOBILE VOLUNTARY COUNSELING AND TESTING";

	String MATERNAL_CHILD_HEALTH_PROGRAM = "MATERNAL CHILD HEALTH PROGRAM";

	String PREVENTION_OF_MOTHER_TO_CHILD_TRANSMISSION_OF_HIV = "PREVENTION OF MOTHER-TO-CHILD TRANSMISSION OF HIV";

	String VOLUNTARY_COUNSELING_AND_TESTING_CENTER = "VOLUNTARY COUNSELING AND TESTING CENTER";

	String TUBERCULOSIS = "TUBERCULOSIS";

	String HOME_BASED_TESTING_PROGRAM = "HOME BASED TESTING PROGRAM";

	String OTHER_NON_CODED = "OTHER NON-CODED";

	String INPATIENT_CARE_OR_HOSPITALIZATION = "INPATIENT CARE OR HOSPITALIZATION";

	String PROVIDER_INITIATED_TESTING_AND_COUNSELING = "PROVIDER INITIATED TESTING AND COUNSELING";

	String PEDIATRIC_OUTPATIENT_CLINIC = "PEDIATRIC OUTPATIENT CLINIC";

	String POINT_OF_HIV_TESTING = "POINT OF HIV TESTING";
        
        //Confirmed HIV date
        String HIV_ENZYME_IMMUNOASSAY_QUALITATIVE = "HIV ENZYME IMMUNOASSAY, QUALITATIVE";
	
	}
