/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */

package org.openmrs.module.amrsreport.rule;

public interface EvaluableNameConstants {

	String ADMITTED_TO_HOSPITAL = "ADMITTED TO HOSPITAL";

	String ALL = "ALL";

	String AMPHOTERICIN_B = "AMPHOTERICIN B";

	String ANTIRETROVIRAL_PLAN = "ANTIRETROVIRAL PLAN";

	String ANTIRETROVIRAL_DRUGS = "ANTIRETROVIRAL DRUGS";

	String ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String ANTIRETROVIRALS_STARTED = "ANTIRETROVIRALS STARTED";

	String CD4_COUNT = "CD4 COUNT";

	String CD4_PANEL = "CD4 PANEL";

	String CD4_PERCENT = "CD4 PERCENT";

	String CHEMISTRY_LAB_TESTS = "CHEMISTRY LAB TESTS";

	String COMPLETE_BLOOD_COUNT = "COMPLETE BLOOD COUNT";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TRANSMISSION_PROPHYLAXIS = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TRANSMISSION PROPHYLAXIS";

	String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT";

	String CRYPTOCOCCAL_TREATMENT_PLAN = "CRYPTOCOCCAL TREATMENT PLAN";

	String CXR = "CXR";

	String CXR_CAVITARY_LESION = "CAVITARY LESION";

	String CXR_DIFFUSE_NON_MILIARY_CHANGES = "DIFFUSE NON-MILIARY CHANGES";

	String CXR_INFILTRATE = "INFILTRATE";

	String CXR_MILIARY_CHANGES = "MILIARY CHANGES";

	String CXR_PULMONARY_EFFUSION = "PULMONARY EFFUSION";

	String DID_NOT_RECIEVE_ANTENATAL_CARE_SERVICE_THIS_VISIT = "DID NOT RECIEVE ANTENATAL CARE SERVICE THIS VISIT";

	String DOSING_CHANGE = "DOSING CHANGE";

	String DRUG_RESTART = "DRUG RESTART";

	String ESTIMATED_DATE_OF_CONFINEMENT = "ESTIMATED DATE OF CONFINEMENT";

	String EXPRESS_CARE_PROGRAM = "EXPRESS CARE PROGRAM";

	String FIRST_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 1";

	String FLUCONAZOLE = "FLUCONAZOLE";

	String HEMOGLOBIN = "HEMOGLOBIN";

	String HIV_INFECTED = "HIV INFECTED";

	String HIV_RAPID_TEST_QUALITATIVE = "HIV RAPID TEST, QUALITATIVE";

	String HIV_TEST_RESULT_PREVIOUSLY = "HIV TEST RESULT PREVIOUSLY";

	String HIV_TEST_RESULT_THIS_VISIT = "HIV TEST RESULT THIS VISIT";

	String HIV_VIRAL_LOAD_QUANTITATIVE = "HIV VIRAL LOAD, QUANTITATIVE";

	String INDIRECT_COOMBS_TEST = "INDIRECT COOMB'S TEST";

	String LAST_MENSTRUAL_PERIOD_DATE = "LAST MENSTRUAL PERIOD DATE";

	String LOW_RISK_EXPRESS_CARE_PROGRAM = "LOW RISK EXPRESS CARE PROGRAM";

	String MEDICATION_ADDED = "MEDICATION ADDED";

	String MULTIDRUG_RESISTANT_TUBERCULOSIS_REGIMEN = "MULTIDRUG-RESISTANT TUBERCULOSIS REGIMEN";

	String MULTIVITAMIN = "MULTIVITAMIN";

	String NEGATIVE = "NEGATIVE";

	String NEVIRAPINE = "NEVIRAPINE";

	String NO = "NO";

	String NONE = "NONE";

	String NUMBER_OF_DOSES_ORDERED = "NUMBER OF DOSES";

	String NUMBER_OF_WEEKS_PREGNANT = "NUMBER OF WEEKS PREGNANT";

	String NUMBER_OF_WEEKS_ON_TREATMENT = "NUMBER OF WEEKS ON TREATMENT";

	String NUTRITIONAL_SUPPORT = "NUTRITIONAL SUPPORT";

	String PARTUM_ANTIRETROVIRAL_USE = "PARTUM ANTIRETROVIRAL USE";

	String PARTUM_DOSING_PERIOD = "PARTUM DOSING PERIOD";

	String PATIENT_REPORTED_CURRENT_TUBERCULOSIS_TREATMENT = "PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT";

	String PATIENT_REPORTED_PAST_ANTIRETROVIRAL_TREATMENT = "PATIENT REPORTED PAST ANTIRETROVIRAL TREATMENT";

	String PATIENT_REPORTED_PROBLEM_ADDED = "PATIENT REPORTED PROBLEM ADDED";
	
	String CONTINUE_REGIMEN="CONTINUE REGIMEN";
	
//constants for CTX startdate and stopdate
	
	String 	PCP_PROPHYLAXIS_STARTED = "PCP PROPHYLAXIS STARTED";
	
	String  REASON_PCP_PROPHYLAXIS_STOPPED="REASON PCP PROPHYLAXIS STOPPED";
	
	String 	REASON_PCP_PROPHYLAXIS_STOPPED_DETAILED="REASON PCP PROPHYLAXIS STOPPED, DETAILED";
	
	String  CURRENT_MEDICATIONS="CURRENT MEDICATIONS";
	
	String TRIMETHOPRIM_AND_SULFAMETHOXAZOLE = "TRIMETHOPRIM AND SULFAMETHOXAZOLE";
	
	String PATIENT_REPORTED_CURRENT_PCP_PROPHYLAXIS ="PATIENT REPORTED CURRENT PCP PROPHYLAXIS";
	
	String TUBERCULOSIS_TREATMENT_COMPLETED_DATE="TUBERCULOSIS TREATMENT COMPLETED DATE";
	
	String TUBERCULOSIS_DRUG_TREATMENT_START_DATE="TUBERCULOSIS DRUG TREATMENT START DATE";
	
	
	//String ENCOUNTER_FETCH_SIZE="ENCOUNTER FETCH SIZE";
	
	//String OBS_ENCOUNTER="OBS ENCOUNTER";
	
//end of constants for CTX startdate and stopdate

	String PCP_PROPHYLAXIS_PLAN = "PCP PROPHYLAXIS PLAN";

	String PEDS_WHO_CATEGORY_QUERY = "PEDS WHO CATEGORY QUERY";

	String POSITIVE = "POSITIVE";

	String PREFERRED_MODE_OF_DELIVERY = "PREFERRED MODE OF DELIVERY";

	String PRESENCE_OF_SUGAR = "PRESENCE OF SUGAR";

	String PROBLEM_ADDED = "PROBLEM ADDED";

	String PROBLEM_RESOLVED = "PROBLEM RESOLVED";

	String PYRAZINAMIDE = "PYRAZINAMIDE";

	String QUANTITY = "QUANTITY";

	String REFERRALS_ORDERED = "REFERRALS ORDERED";

	String REFERRAL_CONSULTANT = "CONSULTANT";

	String REFERRAL_MEDICAL_OFFICER = "MEDICAL OFFICER";

	String REFILLED = "REFILLED";

	String RHESUS_FACTOR = "RHESUS FACTOR";

	String RETURN_VISIT_DATE = "RETURN VISIT DATE";

	String RIFAMPICIN = "RIFAMPICIN";

	String RITONAVIR = "RITONAVIR";

	String SECOND_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 2";

	String SERUM_CREATININE = "SERUM CREATININE";

	String SERUM_ELECTROLYTES = "SERUM ELECTROLYTES";

	String SERUM_GLUTAMIC_PYRUVIC_TRANSAMINASE = "SERUM GLUTAMIC-PYRUVIC TRANSAMINASE";

	String START_DRUGS = "START DRUGS";

	String STOP_ALL = "STOP ALL";

	String TENOFOVIR = "TENOFOVIR";

	String TETANUS_BOOSTER = "TETANUS BOOSTER";

	String TETANUS_BOOSTER_COMPLETED = "TETANUS BOOSTER COMPLETED";

	String TETANUS_BOOSTER_DETAILED = "TETANUS BOOSTER, DETAILED";

	String TESTS_ORDERED = "TESTS ORDERED";

	String TUBERCULOSIS_PROPHYLAXIS_PLAN = "TUBERCULOSIS PROPHYLAXIS PLAN";

	String TUBERCULOSIS_TREATMENT_DRUGS = "TUBERCULOSIS TREATMENT DRUGS";

	String TUBERCULOSIS_TREATMENT_PLAN = "TUBERCULOSIS TREATMENT PLAN";

	String TUBERCULOSIS_DEFAULTER_REGIMEN_BY_USING_STREPTOMYCIN = "TUBERCULOSIS DEFAULTER REGIMEN BY USING STREPTOMYCIN";

	String TUBERCULOSIS_TREATMENT_STARTED = "TUBERCULOSIS TREATMENT STARTED";

	String ENCOUNTER_TYPE_ANCINITIAL = "ANCINITIAL";

	String ENCOUNTER_TYPE_ANCRETURN = "ANCRETURN";

	String ENCOUNTER_TYPE_ADULT_INITIAL = "ADULTINITIAL";

	String ENCOUNTER_TYPE_ADULT_RETURN = "ADULTRETURN";

	String ENCOUNTER_TYPE_ADULT_NONCLINICALMEDICATION = "ADULTNONCLINICALMEDICATION";

	String ENCOUNTER_TYPE_PEDIATRIC_INITIAL = "PEDSINITIAL";

	String ENCOUNTER_TYPE_PEDIATRIC_RETURN = "PEDSRETURN";

	String ENCOUNTER_TYPE_PEDIATRIC_NONCLINICALMEDICATION = "PEDSNONCLINICALMEDICATION";

	String ECSTABLE = "ECSTABLE";
	//Additional concepts for cryptococcal rule
	String ITRACONAZOLE ="ITRACONAZOLE";
	
	//Additional concepts for Entry Point rule
	String MOBILE_VOLUNTARY_COUNSELING_AND_TESTING = "MOBILE VOLUNTARY COUNSELING AND TESTING";

	String MATERNAL_CHILD_HEALTH_PROGRAM = "MATERNAL CHILD HEALTH PROGRAM";

	String PREVENTION_OF_MOTHER_TO_CHILD_TRANSMISSION_OF_HIV = "PREVENTION OF MOTHER-TO-CHILD TRANSMISSION OF HIV";

	String VOLUNTARY_COUNSELING_AND_TESTING_CENTER = "VOLUNTARY COUNSELING AND TESTING CENTER";

	String TUBERCULOSIS = "TUBERCULOSIS";

	String HOME_BASED_TESTING_PROGRAM = "HOME BASED TESTING PROGRAM";

	String OTHER_NON_CODED = "OTHER NON-CODED";

	String INPATIENT_CARE_OR_HOSPITALIZATION = "INPATIENT CARE OR HOSPITALIZATION";

	String PROVIDER_INITIATED_TESTING_AND_COUNSELING = "PROVIDER INITIATED TESTING AND COUNSELING";

	String PEDIATRIC_OUTPATIENT_CLINIC = "PEDIATRIC OUTPATIENT CLINIC";

	String POINT_OF_HIV_TESTING = "POINT OF HIV TESTING";
        
        //Confirmed HIV date
        String HIV_ENZYME_IMMUNOASSAY_QUALITATIVE = "HIV ENZYME IMMUNOASSAY, QUALITATIVE";

		String CRYPTOCOSSUS_TREATMENT_STARTED = "CRYPTOCOSSUS TREATMENT STARTED";

		
		//Additional Concepts for ART Treatment start date rule
		String ANTIRETROVIRAL_DRUG_TREATMENT_START_DATE = "ANTIRETROVIRAL DRUG TREATMENT START DATE";

		String CHANGE_FORMULATION = "CHANGE FORMULATION";

		String CHANGE_REGIMEN = "CHANGE REGIMEN";

		String NOT_REFILLED = "NOT REFILLED";

		String DRUG_SUBSTITUTION = " DRUG SUBSTITUTION";

		String REASON_ANTIRETROVIRALS_STARTED = "REASON ANTIRETROVIRALS STARTED ";

		String TOTAL_MATERNAL_TO_CHILD_TRANSMISSION_PROPHYLAXIS = " TOTAL MATERNAL TO CHILD TRANSMISSION PROPHYLAXIS";

		String PATIENT_REPORTED_REASON_FOR_CURRENT_ANTIRETROVIRALS_STARTED = "PATIENT REPORTED REASON FOR CURRENT ANTIRETROVIRALS STARTED";

		String NEWBORN_ANTIRETROVIRAL_USE = "NEWBORN ANTIRETROVIRAL USE";

		String STAVUDINE = "STAVUDINE";

		String LAMIVUDINE = "LAMIVUDINE";

		String NELFINAVIR = "NELFINAVIR";

		String LOPINAVIR = "LOPINAVIR";

		String ZIDOVUDINE = " ZIDOVUDINE";

		String NEWBORN_PROPHYLACTIC_ANTIRETROVIRAL_USE = "NEWBORN PROPHYLACTIC ANTIRETROVIRAL USE";

		String YES = "YES";
		
		//End of  Additional Concepts for ART Treatment start date rule
		//TRANSFER WITHIN AMPATH LOCATIONS
		String TRANSFER_CARE_TO_OTHER_CENTER="TRANSFER CARE TO OTHER CENTER";
		
		String WITHIN_AMPATH_CLINICS="AMPATH";
		
		String REASON_FOR_MISSED_VISIT="REASON FOR MISSED VISIT";
		
		String AMPATH_CLINIC_TRANSFER="AMPATH CLINIC TRANSFER";
		
		String TRANSFER_CARE_TO_OTHER_CENTER_DETAILED="TRANSFER CARE TO OTHER CENTER, DETAILED";
		
		String FREETEXT_GENERAL="FREETEXT, GENERAL";
		
		
		//Additional Concepts for WHO Stage Rule
		String WHO_STAGE_1_ADULT="WHO STAGE 1 ADULT";
		String WHO_STAGE_2_ADULT="WHO STAGE 2 ADULT";
		String HIV_STAGING_ADULT_HERPES_ZOSTER="HIV STAGING - ADULT HERPES ZOSTER";
		String HIV_STAGING_MINOR_MUCOCUTANEOUS_MANIFESTATIONS="HIV STAGING - MINOR MUCOCUTANEOUS MANIFESTATIONS";
		String HIV_STAGING_WEIGHT_LOSS_LESS_THAN_TEN_PERCENT="HIV STAGING - WEIGHT LOSS LESS THAN TEN PERCENT";
		String ANGULAR_CHEILITIS="ANGULAR CHEILITIS";
		String SEBORRHEIC_DERMATITIS="SEBORRHEIC DERMATITIS";
		String WHO_STAGE_3_ADULT="WHO STAGE 3 ADULT";
		String HIV_STAGING_SERIOUS_BACTERIAL_INFECTIONS="HIV STAGING - SERIOUS BACTERIAL INFECTIONS";
		String HIV_STAGING_TUBERCULOSIS_WITHIN_YEAR="HIV STAGING - TUBERCULOSIS WITHIN YEAR";
		String HIV_STAGING_WEIGHT_LOSS_GREATER_THAN_TEN_PERCENT="HIV STAGING - WEIGHT LOSS GREATER THAN TEN PERCENT";
		String CONFIRMED_HIV_STAGING_WEIGHT_LOSS_GREATER_THAN_TEN_PERCENT="CONFIRMED HIV STAGING - WEIGHT LOSS GREATER THAN TEN PERCENT";
		String CONFIRMED_HIV_STAGING_DIARRHEA_CHRONIC="CONFIRMED HIV STAGING - DIARRHEA, CHRONIC";
		String CONFIRMED_HIV_STAGING_PERSISTENT_CANDIDIASIS_ORAL="CONFIRMED HIV STAGING - PERSISTENT CANDIDIASIS, ORAL";
		String CONFIRMED_HIV_STAGING_PERSISTENT_FEVER="CONFIRMED HIV STAGING - PERSISTENT FEVER";
		String CONFIRMED_WHO_STAGING_ORAL_HAIRY_LEUKOPLAKIA="CONFIRMED WHO STAGING - ORAL HAIRY LEUKOPLAKIA";
		String CONFIRMED_HIV_STAGING_TUBERCULOSIS_PULMONARY="CONFIRMED HIV STAGING - TUBERCULOSIS, PULMONARY";
		String CONFIRMED_HIV_STAGING_SEVERE_BACTERIAL_INFECTIONS="CONFIRMED HIV STAGING - SEVERE BACTERIAL INFECTIONS";
		String CONFIRMED_HIV_STAGING_UNEXPLAINED_ANAEMIA_NEUTROPAENIA="CONFIRMED HIV STAGING - UNEXPLAINED ANAEMIA, NEUTROPAENIA AND/OR CHRONIC THROMBOCYTOPAENIA";
		String CONFIRMED_HIV_STAGING_ACUTE_NECROTIZING_STOMATITIS_GINGIVITIS="CONFIRMED HIV STAGING - ACUTE NECROTIZING STOMATITIS, GINGIVITIS,OR PERIODONTIS";
		String WHO_STAGE_4_ADULT="WHO STAGE 4 ADULT";
		String HIV_STAGING_DISSEMINATED_ENDEMIC_MYCOSIS="HIV STAGING - DISSEMINATED ENDEMIC MYCOSIS";
		String HIV_STAGING_LYMPHOMA="HIV STAGING - LYMPHOMA";
		String HIV_STAGING_MUCOCUTANEOUS_HERPES_SIMPLEX="HIV STAGING - MUCOCUTANEOUS HERPES SIMPLEX";
		String HIV_STAGING_SALMONELLA_SEPTICEMIA="HIV STAGING - SALMONELLA SEPTICEMIA";
		String KAPOSIS_SARCOMA="KAPOSI'S SARCOMA";
		String TOXOPLASMOSIS_CENTRAL_NERVOUS_SYSTEM="TOXOPLASMOSIS, CENTRAL NERVOUS SYSTEM";
		String CONFIRMED_HIV_STAGING_HIV_WASTING_SYNDROME="CONFIRMED HIV STAGING - HIV WASTING SYNDROME";
		String CONFIRMED_HIV_STAGING_PNEUMOCYSTIC_PNEUMONIA="CONFIRMED HIV STAGING - PNEUMOCYSTIC PNEUMONIA";
		String CONFIRMED_HIV_STAGING_RECURRENT_SEVERE_BACTERIAL_PNEUMONIA="CONFIRMED HIV STAGING - RECURRENT SEVERE BACTERIAL PNEUMONIA";
		String CONFIRMED_HIV_STAGING_CHRONIC_HERPES_SIMPLEX="CONFIRMED HIV STAGING - CHRONIC HERPES SIMPLEX";
		String CONFIRMED_HIV_STAGING_CANDIDIASIS="CONFIRMED HIV STAGING - CANDIDIASIS";
		String CONFIRMED_HIV_STAGING_EXTRAPULMONARY_TUBERCULOSIS="CONFIRMED HIV STAGING - EXTRAPULMONARY TUBERCULOSIS";
		String CONFIRMED_HIV_STAGING_KAPOSIS_SARCOMA_KS="CONFIRMED HIV STAGING - KAPOSI'S SARCOMA (KS)";
		String CONFIRMED_HIV_STAGING_CYTOMEGALOVIRUS_DISEASE="CONFIRMED HIV STAGING - CYTOMEGALOVIRUS DISEASE";
		String CONFIRMED_HIV_STAGING_TOXOPLASMOSIS_CNS="CONFIRMED HIV STAGING - TOXOPLASMOSIS, CNS";
		String CONFIRMED_HIV_STAGING_HIV_ENCEPHALOPATHY="CONFIRMED HIV STAGING - HIV ENCEPHALOPATHY";
		String CONFIRMED_HIV_STAGING_CRYPTOCOCCOSIS_EXTRAPULMONARY="CONFIRMED HIV STAGING - CRYPTOCOCCOSIS, EXTRAPULMONARY";
		String CONFIRMED_HIV_STAGING_DISSEMINATED_NON_TUBERCULOSIS_MYCOBACTERIAL_INFECTION="CONFIRMED HIV STAGING - DISSEMINATED NON-TUBERCULOSIS MYCOBACTERIAL INFECTION";
		String CONFIRMED_HIV_STAGING_PROGRESSIVE_MULTIFOCAL_LEUKOENCEPHALOPATHY="CONFIRMED HIV STAGING - PROGRESSIVE MULTIFOCAL LEUKOENCEPHALOPATHY";
		String CONFIRMED_HIV_STAGING_CHRONIC_CRYPTOSPORIDIOSIS="CONFIRMED HIV STAGING - CHRONIC CRYPTOSPORIDIOSIS";
		String CONFIRMED_HIV_STAGING_CHRONIC_ISOSPORIASIS="CONFIRMED HIV STAGING - CHRONIC ISOSPORIASIS";
		String CONFIRMED_HIV_STAGING_DISSEMINATED_MYCOSIS="CONFIRMED HIV STAGING - DISSEMINATED MYCOSIS";
		String CONFIRMED_HIV_STAGING_RECURRENT_SEPTICEMIA="CONFIRMED HIV STAGING - RECURRENT SEPTICEMIA";
		String CONFIRMED_HIV_STAGING_LYMPHOMA="CONFIRMED HIV STAGING - LYMPHOMA";
		String CONFIRMED_HIV_STAGING_INVASIVE_CERVICAL_CARCINOMA="CONFIRMED HIV STAGING - INVASIVE CERVICAL CARCINOMA";
		String CONFIRMED_HIV_STAGING_ATYPICAL_DISSEMINATED_LEISHMANIASIS="CONFIRMED HIV STAGING - ATYPICAL DISSEMINATED LEISHMANIASIS";
		String CONFIRMED_HIV_STAGING_SYMPTOMATIC_HIV_ASSOCIATED_NEPHROPATHY="CONFIRMED HIV STAGING - SYMPTOMATIC HIV-ASSOCIATED NEPHROPATHY OR CARDIOMYOPATHY";
		String WHO_STAGE_1_PEDS="WHO STAGE 1 PEDS";
		String ASYMPTOMATIC_HIV_INFECTION="ASYMPTOMATIC HIV INFECTION";
		String HIV_STAGING_PERSISTENT_GENERALIZED_LYMPHADENOPATHY="HIV STAGING - PERSISTENT GENERALIZED LYMPHADENOPATHY";
		String WHO_STAGE_2_PEDS="WHO STAGE 2 PEDS";
		String DERMATITIS="DERMATITIS";
		String HERPES_ZOSTER="HERPES ZOSTER";
		String HIV_STAGING_HSV_STOMATITIS="	HIV STAGING - HSV STOMATITIS";
		String HIV_STAGING_RECURRENT_UPPER_RESPIRATORY_INFECTION="HIV STAGING - RECURRENT UPPER RESPIRATORY INFECTION";
		String HIV_STAGING_STEROID_RESISTANT_THROMBOCYTOPENIA="HIV STAGING - STEROID RESISTANT THROMBOCYTOPENIA";
		String HUMAN_PAPILLOMAVIRUS="HUMAN PAPILLOMAVIRUS";
		String MOLLUSCUM_CONTAGIOSUM="MOLLUSCUM CONTAGIOSUM";
		String PAROTID_ENLARGEMENT="PAROTID ENLARGEMENT";
		String VERRUCA_PLANUS="VERRUCA PLANUS";
		String RECURRENT_ORAL_ULCERATION="RECURRENT ORAL ULCERATION";
		String PAPULAR_PRURITIC_ERUPTION="PAPULAR PRURITIC ERUPTION";
		String FUNGAL_NAIL_INFECTIONS="FUNGAL NAIL INFECTIONS";
		String LINEAR_GINGIVAL_ERYTHEMA="LINEAR GINGIVAL ERYTHEMA";
		String WARTS_GENITAL="WARTS, GENITAL";
		String CHRONIC_UPPER_RESPIRATORY_TRACT_INFECTIONS="CHRONIC UPPER RESPIRATORY TRACT INFECTIONS";
		String HEPATOSPLENOMEGALY="HEPATOSPLENOMEGALY";
		String WHO_STAGE_3_PEDS="WHO STAGE 3 PEDS";
		String DIARRHEA_CHRONIC="DIARRHEA, CHRONIC";
		String FAILURE_TO_THRIVE="FAILURE TO THRIVE";
		String HIV_STAGING_CANDIDIASIS_ORORESPIRATORY_TRACT="HIV STAGING - CANDIDIASIS, ORORESPIRATORY TRACT";
		String HIV_STAGING_LYMPHOID_INTERSTITIAL_PNEUMONIA="HIV STAGING - LYMPHOID INTERSTITIAL PNEUMONIA";
		String HIV_STAGING_PEDS_HERPES_ZOSTER="HIV STAGING - PEDS HERPES ZOSTER";
		String HIV_STAGING_RECURRENT_BACTERIAL_PNEUMONIA="HIV STAGING - RECURRENT BACTERIAL PNEUMONIA";
		String HIV_STAGING_REFRACTORY_ANEMIA="HIV STAGING - REFRACTORY ANEMIA";
		String HIV_STAGING_VARICELLA_DISSEMINATED="HIV STAGING - VARICELLA, DISSEMINATED";
		String PNEUMONIA_TUBERCULOUS="PNEUMONIA, TUBERCULOUS";
		String RECTOVAGINAL_FISTULA="RECTOVAGINAL FISTULA";
		String HIV_STAGING_MODERATE_MALNUTRITION="HIV STAGING - MODERATE MALNUTRITION";
		String HIV_STAGING_PERSISTENT_FEVER="HIV STAGING - PERSISTENT FEVER";
		String CANDIDIASIS_ORAL="CANDIDIASIS, ORAL";
		String ORAL_HAIRY_LEUKOPLAKIA="ORAL HAIRY LEUKOPLAKIA";
		String LYMPH_NODE_TUBERCULOSIS="LYMPH NODE TUBERCULOSIS";
		String HIV_STAGING_CHRONIC_HIV_ASSOCIATED_LUNG_DISEASE="HIV STAGING - CHRONIC HIV-ASSOCIATED LUNG DISEASE";
		String HIV_STAGING_UNEXAPLINED_ANEMIA_NEUTROPENIA="HIV STAGING - UNEXAPLINED ANEMIA, NEUTROPENIA, OR CHRONIC THROMBOCYTOPENIA";
		String HIV_STAGING_ACUTE_NECROTIZING_ULCERATIVE_GINGIVITIS_PERIODONTIS="HIV STAGING - ACUTE NECROTIZING ULCERATIVE, GINGIVITIS, OR PERIODONTITIS";
		String WHO_STAGE_4_PEDS="WHO STAGE 4 PEDS";
		String CANDIDIASIS="CANDIDIASIS";
		String CARDIOMYOPATHY = "CARDIOMYOPATHY";
		String CRYPTOCOCCOSIS="CRYPTOCOCCOSIS";
		String ENCEPHALOPATHY="ENCEPHALOPATHY";
		String HIV_STAGING_COCCIDIODOMYCOSIS_DISSEMINATED="HIV STAGING - COCCIDIODOMYCOSIS, DISSEMINATED";
		String HIV_STAGING_CRYPTOCOCCOSIS_EXTRAPULMONARY="HIV STAGING - CRYPTOCOCCOSIS, EXTRAPULMONARY";
		String HIV_STAGING_CRYPTOSPORIDIOSIS="HIV STAGING - CRYPTOSPORIDIOSIS";
		String HIV_STAGING_CYTOMEGALOVIRUS_DISEASE="HIV STAGING - CYTOMEGALOVIRUS DISEASE";
		String HIV_STAGING_HISTOPLASMOSIS_DISSEMINATED="HIV STAGING - HISTOPLASMOSIS, DISSEMINATED";
		String HIV_STAGING_MYCOBACTERIUM_OTHER="HIV STAGING - MYCOBACTERIUM, OTHER";
		String HIV_STAGING_NONRESPONSIVE_HERPES_SIMPLEX_VIRUS="HIV STAGING - NONRESPONSIVE HERPES SIMPLEX VIRUS";
		String HIV_STAGING_SEVERE_BACTERIAL_INFECTION="HIV STAGING - SEVERE BACTERIAL INFECTION";
		String NEPHROPATHY="NEPHROPATHY";
		String PNEUMOCYSTIC_CARINII_PNEUMONIA="PNEUMOCYSTIC CARINII PNEUMONIA";
		String PROGRESSIVE_MULTIFOCAL_LEUKOENCEPHALOPATHY="PROGRESSIVE MULTIFOCAL LEUKOENCEPHALOPATHY";
		String TOXOPLASMOSIS="TOXOPLASMOSIS";
		String WASTING_SYNDROME="WASTING SYNDROME";
		String CANDIDIASIS_OESOPHAGEAL="CANDIDIASIS, OESOPHAGEAL";
		String MYCOBACTERIUM_TUBERCULOSIS_EXTRAPULMONARY="MYCOBACTERIUM TUBERCULOSIS, EXTRAPULMONARY";
		String HIV_STAGING_CHRONIC_ISOSPORIASIS="HIV STAGING - CHRONIC ISOSPORIASIS";
		String HIV_STAGING_CEREBRAL_B_CELL_NON_HODGKIN_LYMPHOMA="HIV STAGING - CEREBRAL OR B-CELL NON-HODGKIN LYMPHOMA";
		
		
		//End of Additional Concepts for WHO Stage Rule
		
		//TRANSFER OUTSIDE AMPATH LOCATIONS
		String NON_AMPATH="NON-AMPATH";
		String REASON_EXITED_CARE="REASON EXITED CARE";
		String PATIENT_TRANSFERRED_OUT="PATIENT TRANSFERRED OUT";
		String OUTCOME_AT_END_OF_TUBERCULOSIS_TREATMENT="OUTCOME AT END OF TUBERCULOSIS TREATMENT";

		String PRESUMPTIVE_HIV_STAGING_TUBERCULOSIS_PULMONARY = "PRESUMPTIVE HIV STAGING - TUBERCULOSIS, PULMONARY";

		String OTITIS_MEDIA = "OTITIS MEDIA";
	
	
	}
