/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.amrsreport.rule;

public interface MohEvaluableNameConstants {

	public static final String ADMITTED_TO_HOSPITAL = "ADMITTED TO HOSPITAL";
	public static final String ALL = "ALL";
	public static final String AMPHOTERICIN_B = "AMPHOTERICIN B";
	public static final String ANTIRETROVIRAL_PLAN = "ANTIRETROVIRAL PLAN";
	public static final String ANTIRETROVIRAL_DRUGS = "ANTIRETROVIRAL DRUGS";
	public static final String ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "ANTIRETROVIRAL DRUGS USED FOR TREATMENT";
	public static final String ANTIRETROVIRALS_STARTED = "ANTIRETROVIRALS STARTED";
	public static final String CD4_COUNT = "CD4 COUNT";
	public static final String CD4_PANEL = "CD4 PANEL";
	public static final String CD4_PERCENT = "CD4 PERCENT";
	public static final String CD4_BY_FACS = "CD4, BY FACS";
	public static final String CHEMISTRY_LAB_TESTS = "CHEMISTRY LAB TESTS";
	public static final String COMPLETE_BLOOD_COUNT = "COMPLETE BLOOD COUNT";
	public static final String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TRANSMISSION_PROPHYLAXIS = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TRANSMISSION PROPHYLAXIS";
	public static final String CURRENT_ANTIRETROVIRAL_DRUGS_USED_FOR_TREATMENT = "CURRENT ANTIRETROVIRAL DRUGS USED FOR TREATMENT";
	public static final String CRYPTOCOCCAL_TREATMENT_PLAN = "CRYPTOCOCCAL TREATMENT PLAN";
	public static final String CXR = "CXR";
	public static final String CXR_CAVITARY_LESION = "CAVITARY LESION";
	public static final String CXR_DIFFUSE_NON_MILIARY_CHANGES = "DIFFUSE NON-MILIARY CHANGES";
	public static final String CXR_INFILTRATE = "INFILTRATE";
	public static final String CXR_MILIARY_CHANGES = "MILIARY CHANGES";
	public static final String CXR_PULMONARY_EFFUSION = "PULMONARY EFFUSION";
	public static final String DID_NOT_RECIEVE_ANTENATAL_CARE_SERVICE_THIS_VISIT = "DID NOT RECIEVE ANTENATAL CARE SERVICE THIS VISIT";
	public static final String DOSING_CHANGE = "DOSING CHANGE";
	public static final String DRUG_RESTART = "DRUG RESTART";
	public static final String ESTIMATED_DATE_OF_CONFINEMENT = "ESTIMATED DATE OF CONFINEMENT";
	public static final String EXPRESS_CARE_PROGRAM = "EXPRESS CARE PROGRAM";
	public static final String FIRST_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 1";
	public static final String FLUCONAZOLE = "FLUCONAZOLE";
	public static final String HEMOGLOBIN = "HEMOGLOBIN";
	public static final String HIV_DNA_PCR = "HIV DNA POLYMERASE CHAIN REACTION, QUALITATIVE";
	public static final String HIV_INFECTED = "HIV INFECTED";
	public static final String HIV_RAPID_TEST_QUALITATIVE = "HIV RAPID TEST, QUALITATIVE";
	public static final String HIV_TEST_RESULT_PREVIOUSLY = "HIV TEST RESULT PREVIOUSLY";
	public static final String HIV_TEST_RESULT_THIS_VISIT = "HIV TEST RESULT THIS VISIT";
	public static final String HIV_VIRAL_LOAD_QUANTITATIVE = "HIV VIRAL LOAD, QUANTITATIVE";
	public static final String INDIRECT_COOMBS_TEST = "INDIRECT COOMB'S TEST";
	public static final String LAST_MENSTRUAL_PERIOD_DATE = "LAST MENSTRUAL PERIOD DATE";
	public static final String LOW_RISK_EXPRESS_CARE_PROGRAM = "LOW RISK EXPRESS CARE PROGRAM";
	public static final String MEDICATION_ADDED = "MEDICATION ADDED";
	public static final String MULTIDRUG_RESISTANT_TUBERCULOSIS_REGIMEN = "MULTIDRUG-RESISTANT TUBERCULOSIS REGIMEN";
	public static final String MULTIVITAMIN = "MULTIVITAMIN";
	public static final String NEGATIVE = "NEGATIVE";
	public static final String NEVIRAPINE = "NEVIRAPINE";
	public static final String NO = "NO";
	public static final String NONE = "NONE";
	public static final String NUMBER_OF_DOSES_ORDERED = "NUMBER OF DOSES";
	public static final String NUMBER_OF_WEEKS_PREGNANT = "NUMBER OF WEEKS PREGNANT";
	public static final String NUMBER_OF_WEEKS_ON_TREATMENT = "NUMBER OF WEEKS ON TREATMENT";
	public static final String NUTRITIONAL_SUPPORT = "NUTRITIONAL SUPPORT";
	public static final String PARTUM_ANTIRETROVIRAL_USE = "PARTUM ANTIRETROVIRAL USE";
	public static final String PARTUM_DOSING_PERIOD = "PARTUM DOSING PERIOD";
	public static final String PATIENT_REPORTED_CURRENT_TUBERCULOSIS_TREATMENT = "PATIENT REPORTED CURRENT TUBERCULOSIS TREATMENT";
	public static final String PATIENT_REPORTED_PAST_ANTIRETROVIRAL_TREATMENT = "PATIENT REPORTED PAST ANTIRETROVIRAL TREATMENT";
	public static final String PATIENT_REPORTED_PROBLEM_ADDED = "PATIENT REPORTED PROBLEM ADDED";
	public static final String CONTINUE_REGIMEN = "CONTINUE REGIMEN";
	
	//constants for CTX startdate and stopdate
	public static final String PCP_PROPHYLAXIS_STARTED = "PCP PROPHYLAXIS STARTED";
	public static final String REASON_PCP_PROPHYLAXIS_STOPPED = "REASON PCP PROPHYLAXIS STOPPED";
	public static final String REASON_PCP_PROPHYLAXIS_STOPPED_DETAILED = "REASON PCP PROPHYLAXIS STOPPED, DETAILED";
	public static final String CURRENT_MEDICATIONS = "CURRENT MEDICATIONS";
	public static final String TRIMETHOPRIM_AND_SULFAMETHOXAZOLE = "TRIMETHOPRIM AND SULFAMETHOXAZOLE";
	public static final String PATIENT_REPORTED_CURRENT_PCP_PROPHYLAXIS = "PATIENT REPORTED CURRENT PCP PROPHYLAXIS";
	public static final String TUBERCULOSIS_TREATMENT_COMPLETED_DATE = "TUBERCULOSIS TREATMENT COMPLETED DATE";
	public static final String TUBERCULOSIS_DRUG_TREATMENT_START_DATE = "TUBERCULOSIS DRUG TREATMENT START DATE";
	public static final String CD4_COUNT_GREATER_THAN_15 = "CD4 COUNT GREATER THAN 15%";
	public static final String WEIGHT_CHANGE = "WEIGHT CHANGE";
	public static final String CD4_COUNT_GREATER_THAN_200 = "CD4 COUNT GREATER THAN 200";
	public static final String TOXICITY_DRUG = "TOXICITY, DRUG";
	//public static final String OTHER_NON_CODED = "OTHER NON-CODED";
	//end of constants for CTX startdate and stopdate
	
	public static final String PCP_PROPHYLAXIS_PLAN = "PCP PROPHYLAXIS PLAN";
	public static final String PEDS_WHO_CATEGORY_QUERY = "PEDS WHO CATEGORY QUERY";
	public static final String POSITIVE = "POSITIVE";
	public static final String PREFERRED_MODE_OF_DELIVERY = "PREFERRED MODE OF DELIVERY";
	public static final String PRESENCE_OF_SUGAR = "PRESENCE OF SUGAR";
	public static final String PROBLEM_ADDED = "PROBLEM ADDED";
	public static final String PROBLEM_RESOLVED = "PROBLEM RESOLVED";
	public static final String PYRAZINAMIDE = "PYRAZINAMIDE";
	public static final String QUANTITY = "QUANTITY";
	public static final String REFERRALS_ORDERED = "REFERRALS ORDERED";
	public static final String REFERRAL_CONSULTANT = "CONSULTANT";
	public static final String REFERRAL_MEDICAL_OFFICER = "MEDICAL OFFICER";
	public static final String REFILLED = "REFILLED";
	public static final String RHESUS_FACTOR = "RHESUS FACTOR";
	public static final String RETURN_VISIT_DATE = "RETURN VISIT DATE";
	public static final String RIFAMPICIN = "RIFAMPICIN";
	public static final String RITONAVIR = "RITONAVIR";
	public static final String SECOND_INTERMITTENT_PREVENTIVE_TREATMENT = "INTERMITTENT PREVENTIVE TREATMENT 2";
	public static final String SERUM_CREATININE = "SERUM CREATININE";
	public static final String SERUM_ELECTROLYTES = "SERUM ELECTROLYTES";
	public static final String SERUM_GLUTAMIC_PYRUVIC_TRANSAMINASE = "SERUM GLUTAMIC-PYRUVIC TRANSAMINASE";
	public static final String START_DRUGS = "START DRUGS";
	public static final String STOP_ALL = "STOP ALL";
	public static final String TENOFOVIR = "TENOFOVIR";
	public static final String TETANUS_BOOSTER = "TETANUS BOOSTER";
	public static final String TETANUS_BOOSTER_COMPLETED = "TETANUS BOOSTER COMPLETED";
	public static final String TETANUS_BOOSTER_DETAILED = "TETANUS BOOSTER, DETAILED";
	public static final String TESTS_ORDERED = "TESTS ORDERED";
	public static final String TUBERCULOSIS_PROPHYLAXIS_PLAN = "TUBERCULOSIS PROPHYLAXIS PLAN";
	public static final String TUBERCULOSIS_TREATMENT_DRUGS = "TUBERCULOSIS TREATMENT DRUGS";
	public static final String TUBERCULOSIS_TREATMENT_PLAN = "TUBERCULOSIS TREATMENT PLAN";
	public static final String TUBERCULOSIS_DEFAULTER_REGIMEN_BY_USING_STREPTOMYCIN = "TUBERCULOSIS DEFAULTER REGIMEN BY USING STREPTOMYCIN";
	public static final String TUBERCULOSIS_TREATMENT_STARTED = "TUBERCULOSIS DRUG TREATMENT START DATE";
	public static final String ENCOUNTER_TYPE_ANCINITIAL = "ANCINITIAL";
	public static final String ENCOUNTER_TYPE_ANCRETURN = "ANCRETURN";
	public static final String ENCOUNTER_TYPE_ADULT_INITIAL = "ADULTINITIAL";
	public static final String ENCOUNTER_TYPE_ADULT_RETURN = "ADULTRETURN";
	public static final String ENCOUNTER_TYPE_ADULT_NONCLINICALMEDICATION = "ADULTNONCLINICALMEDICATION";
	public static final String ENCOUNTER_TYPE_PEDIATRIC_INITIAL = "PEDSINITIAL";
	public static final String ENCOUNTER_TYPE_PEDIATRIC_RETURN = "PEDSRETURN";
	public static final String ENCOUNTER_TYPE_PEDIATRIC_NONCLINICALMEDICATION = "PEDSNONCLINICALMEDICATION";
	public static final String ECSTABLE = "ECSTABLE";
	
	//Additional concepts for cryptococcal rule
	public static final String ITRACONAZOLE = "ITRACONAZOLE";
	
	//Additional concepts for Entry Point rule
	public static final String MOBILE_VOLUNTARY_COUNSELING_AND_TESTING = "MOBILE VOLUNTARY COUNSELING AND TESTING";
	public static final String MATERNAL_CHILD_HEALTH_PROGRAM = "MATERNAL CHILD HEALTH PROGRAM";
	public static final String PREVENTION_OF_MOTHER_TO_CHILD_TRANSMISSION_OF_HIV = "PREVENTION OF MOTHER-TO-CHILD TRANSMISSION OF HIV";
	public static final String VOLUNTARY_COUNSELING_AND_TESTING_CENTER = "VOLUNTARY COUNSELING AND TESTING CENTER";
	public static final String TUBERCULOSIS = "TUBERCULOSIS";
	public static final String HOME_BASED_TESTING_PROGRAM = "HOME BASED TESTING PROGRAM";
	public static final String OTHER_NON_CODED = "OTHER NON-CODED";
	public static final String INPATIENT_CARE_OR_HOSPITALIZATION = "INPATIENT CARE OR HOSPITALIZATION";
	public static final String PROVIDER_INITIATED_TESTING_AND_COUNSELING = "PROVIDER INITIATED TESTING AND COUNSELING";
	public static final String PEDIATRIC_OUTPATIENT_CLINIC = "PEDIATRIC OUTPATIENT CLINIC";
	public static final String POINT_OF_HIV_TESTING = "POINT OF HIV TESTING";
	
	//Confirmed HIV date
	String HIV_ENZYME_IMMUNOASSAY_QUALITATIVE = "HIV ENZYME IMMUNOASSAY, QUALITATIVE";
	String CRYPTOCOSSUS_TREATMENT_STARTED = "CRYPTOCOSSUS TREATMENT STARTED";

	//Additional Concepts for ART Treatment start date rule
	public static final String ANTIRETROVIRAL_DRUG_TREATMENT_START_DATE = "ANTIRETROVIRAL DRUG TREATMENT START DATE";
	public static final String CHANGE_FORMULATION = "CHANGE FORMULATION";
	public static final String CHANGE_REGIMEN = "CHANGE REGIMEN";
	public static final String NOT_REFILLED = "NOT REFILLED";
	public static final String DRUG_SUBSTITUTION = " DRUG SUBSTITUTION";
	public static final String REASON_ANTIRETROVIRALS_STARTED = "REASON ANTIRETROVIRALS STARTED ";
	public static final String TOTAL_MATERNAL_TO_CHILD_TRANSMISSION_PROPHYLAXIS = " TOTAL MATERNAL TO CHILD TRANSMISSION PROPHYLAXIS";
	public static final String PATIENT_REPORTED_REASON_FOR_CURRENT_ANTIRETROVIRALS_STARTED = "PATIENT REPORTED REASON FOR CURRENT ANTIRETROVIRALS STARTED";
	public static final String NEWBORN_ANTIRETROVIRAL_USE = "NEWBORN ANTIRETROVIRAL USE";
	public static final String STAVUDINE = "STAVUDINE";
	public static final String LAMIVUDINE = "LAMIVUDINE";
	public static final String NELFINAVIR = "NELFINAVIR";
	public static final String LOPINAVIR = "LOPINAVIR";
	public static final String ZIDOVUDINE = " ZIDOVUDINE";
	public static final String NEWBORN_PROPHYLACTIC_ANTIRETROVIRAL_USE = "NEWBORN PROPHYLACTIC ANTIRETROVIRAL USE";
	public static final String YES = "YES";
	//End of  Additional Concepts for ART Treatment start date rule
	
	//TRANSFER WITHIN AMPATH LOCATIONS
	public static final String TRANSFER_CARE_TO_OTHER_CENTER = "TRANSFER CARE TO OTHER CENTER";
	public static final String WITHIN_AMPATH_CLINICS = "AMPATH";
	public static final String REASON_FOR_MISSED_VISIT = "REASON FOR MISSED VISIT";
	public static final String AMPATH_CLINIC_TRANSFER = "AMPATH CLINIC TRANSFER";
	public static final String TRANSFER_CARE_TO_OTHER_CENTER_DETAILED = "TRANSFER CARE TO OTHER CENTER, DETAILED";
	public static final String FREETEXT_GENERAL = "FREETEXT, GENERAL";
	
	//Additional Concepts for WHO Stage Rule
	public static final String WHO_STAGE_ADULT = "CURRENT WHO HIV STAGE";
	public static final String WHO_STAGE_1_ADULT = "WHO STAGE 1 ADULT";
	public static final String WHO_STAGE_2_ADULT = "WHO STAGE 2 ADULT";
	public static final String WHO_STAGE_3_ADULT = "WHO STAGE 3 ADULT";
	public static final String WHO_STAGE_4_ADULT = "WHO STAGE 4 ADULT";
	public static final String WHO_STAGE_PEDS = "PEDS WHO CATEGORY QUERY";
	public static final String WHO_STAGE_1_PEDS = "WHO STAGE 1 PEDS";
	public static final String WHO_STAGE_2_PEDS = "WHO STAGE 2 PEDS";
	public static final String WHO_STAGE_3_PEDS = "WHO STAGE 3 PEDS";
	public static final String WHO_STAGE_4_PEDS = "WHO STAGE 4 PEDS";
	public static final String HIV_STAGING_ADULT_HERPES_ZOSTER = "HIV STAGING - ADULT HERPES ZOSTER";
	public static final String HIV_STAGING_MINOR_MUCOCUTANEOUS_MANIFESTATIONS = "HIV STAGING - MINOR MUCOCUTANEOUS MANIFESTATIONS";
	public static final String HIV_STAGING_WEIGHT_LOSS_LESS_THAN_TEN_PERCENT = "HIV STAGING - WEIGHT LOSS LESS THAN TEN PERCENT";
	public static final String ANGULAR_CHEILITIS = "ANGULAR CHEILITIS";
	public static final String SEBORRHEIC_DERMATITIS = "SEBORRHEIC DERMATITIS";
	public static final String HIV_STAGING_SERIOUS_BACTERIAL_INFECTIONS = "HIV STAGING - SERIOUS BACTERIAL INFECTIONS";
	public static final String HIV_STAGING_TUBERCULOSIS_WITHIN_YEAR = "HIV STAGING - TUBERCULOSIS WITHIN YEAR";
	public static final String HIV_STAGING_WEIGHT_LOSS_GREATER_THAN_TEN_PERCENT = "HIV STAGING - WEIGHT LOSS GREATER THAN TEN PERCENT";
	public static final String CONFIRMED_HIV_STAGING_WEIGHT_LOSS_GREATER_THAN_TEN_PERCENT = "CONFIRMED HIV STAGING - WEIGHT LOSS GREATER THAN TEN PERCENT";
	public static final String CONFIRMED_HIV_STAGING_DIARRHEA_CHRONIC = "CONFIRMED HIV STAGING - DIARRHEA, CHRONIC";
	public static final String CONFIRMED_HIV_STAGING_PERSISTENT_CANDIDIASIS_ORAL = "CONFIRMED HIV STAGING - PERSISTENT CANDIDIASIS, ORAL";
	public static final String CONFIRMED_HIV_STAGING_PERSISTENT_FEVER = "CONFIRMED HIV STAGING - PERSISTENT FEVER";
	public static final String CONFIRMED_WHO_STAGING_ORAL_HAIRY_LEUKOPLAKIA = "CONFIRMED WHO STAGING - ORAL HAIRY LEUKOPLAKIA";
	public static final String CONFIRMED_HIV_STAGING_TUBERCULOSIS_PULMONARY = "CONFIRMED HIV STAGING - TUBERCULOSIS, PULMONARY";
	public static final String CONFIRMED_HIV_STAGING_SEVERE_BACTERIAL_INFECTIONS = "CONFIRMED HIV STAGING - SEVERE BACTERIAL INFECTIONS";
	public static final String CONFIRMED_HIV_STAGING_UNEXPLAINED_ANAEMIA_NEUTROPAENIA = "CONFIRMED HIV STAGING - UNEXPLAINED ANAEMIA, NEUTROPAENIA AND/OR CHRONIC THROMBOCYTOPAENIA";
	public static final String CONFIRMED_HIV_STAGING_ACUTE_NECROTIZING_STOMATITIS_GINGIVITIS = "CONFIRMED HIV STAGING - ACUTE NECROTIZING STOMATITIS, GINGIVITIS,OR PERIODONTIS";
	public static final String HIV_STAGING_DISSEMINATED_ENDEMIC_MYCOSIS = "HIV STAGING - DISSEMINATED ENDEMIC MYCOSIS";
	public static final String HIV_STAGING_LYMPHOMA = "HIV STAGING - LYMPHOMA";
	public static final String HIV_STAGING_MUCOCUTANEOUS_HERPES_SIMPLEX = "HIV STAGING - MUCOCUTANEOUS HERPES SIMPLEX";
	public static final String HIV_STAGING_SALMONELLA_SEPTICEMIA = "HIV STAGING - SALMONELLA SEPTICEMIA";
	public static final String KAPOSIS_SARCOMA = "KAPOSI'S SARCOMA";
	public static final String TOXOPLASMOSIS_CENTRAL_NERVOUS_SYSTEM = "TOXOPLASMOSIS, CENTRAL NERVOUS SYSTEM";
	public static final String CONFIRMED_HIV_STAGING_HIV_WASTING_SYNDROME = "CONFIRMED HIV STAGING - HIV WASTING SYNDROME";
	public static final String CONFIRMED_HIV_STAGING_PNEUMOCYSTIC_PNEUMONIA = "CONFIRMED HIV STAGING - PNEUMOCYSTIC PNEUMONIA";
	public static final String CONFIRMED_HIV_STAGING_RECURRENT_SEVERE_BACTERIAL_PNEUMONIA = "CONFIRMED HIV STAGING - RECURRENT SEVERE BACTERIAL PNEUMONIA";
	public static final String CONFIRMED_HIV_STAGING_CHRONIC_HERPES_SIMPLEX = "CONFIRMED HIV STAGING - CHRONIC HERPES SIMPLEX";
	public static final String CONFIRMED_HIV_STAGING_CANDIDIASIS = "CONFIRMED HIV STAGING - CANDIDIASIS";
	public static final String CONFIRMED_HIV_STAGING_EXTRAPULMONARY_TUBERCULOSIS = "CONFIRMED HIV STAGING - EXTRAPULMONARY TUBERCULOSIS";
	public static final String CONFIRMED_HIV_STAGING_KAPOSIS_SARCOMA_KS = "CONFIRMED HIV STAGING - KAPOSI'S SARCOMA (KS)";
	public static final String CONFIRMED_HIV_STAGING_CYTOMEGALOVIRUS_DISEASE = "CONFIRMED HIV STAGING - CYTOMEGALOVIRUS DISEASE";
	public static final String CONFIRMED_HIV_STAGING_TOXOPLASMOSIS_CNS = "CONFIRMED HIV STAGING - TOXOPLASMOSIS, CNS";
	public static final String CONFIRMED_HIV_STAGING_HIV_ENCEPHALOPATHY = "CONFIRMED HIV STAGING - HIV ENCEPHALOPATHY";
	public static final String CONFIRMED_HIV_STAGING_CRYPTOCOCCOSIS_EXTRAPULMONARY = "CONFIRMED HIV STAGING - CRYPTOCOCCOSIS, EXTRAPULMONARY";
	public static final String CONFIRMED_HIV_STAGING_DISSEMINATED_NON_TUBERCULOSIS_MYCOBACTERIAL_INFECTION = "CONFIRMED HIV STAGING - DISSEMINATED NON-TUBERCULOSIS MYCOBACTERIAL INFECTION";
	public static final String CONFIRMED_HIV_STAGING_PROGRESSIVE_MULTIFOCAL_LEUKOENCEPHALOPATHY = "CONFIRMED HIV STAGING - PROGRESSIVE MULTIFOCAL LEUKOENCEPHALOPATHY";
	public static final String CONFIRMED_HIV_STAGING_CHRONIC_CRYPTOSPORIDIOSIS = "CONFIRMED HIV STAGING - CHRONIC CRYPTOSPORIDIOSIS";
	public static final String CONFIRMED_HIV_STAGING_CHRONIC_ISOSPORIASIS = "CONFIRMED HIV STAGING - CHRONIC ISOSPORIASIS";
	public static final String CONFIRMED_HIV_STAGING_DISSEMINATED_MYCOSIS = "CONFIRMED HIV STAGING - DISSEMINATED MYCOSIS";
	public static final String CONFIRMED_HIV_STAGING_RECURRENT_SEPTICEMIA = "CONFIRMED HIV STAGING - RECURRENT SEPTICEMIA";
	public static final String CONFIRMED_HIV_STAGING_LYMPHOMA = "CONFIRMED HIV STAGING - LYMPHOMA";
	public static final String CONFIRMED_HIV_STAGING_INVASIVE_CERVICAL_CARCINOMA = "CONFIRMED HIV STAGING - INVASIVE CERVICAL CARCINOMA";
	public static final String CONFIRMED_HIV_STAGING_ATYPICAL_DISSEMINATED_LEISHMANIASIS = "CONFIRMED HIV STAGING - ATYPICAL DISSEMINATED LEISHMANIASIS";
	public static final String CONFIRMED_HIV_STAGING_SYMPTOMATIC_HIV_ASSOCIATED_NEPHROPATHY = "CONFIRMED HIV STAGING - SYMPTOMATIC HIV-ASSOCIATED NEPHROPATHY OR CARDIOMYOPATHY";
	public static final String ASYMPTOMATIC_HIV_INFECTION = "ASYMPTOMATIC HIV INFECTION";
	public static final String HIV_STAGING_PERSISTENT_GENERALIZED_LYMPHADENOPATHY = "HIV STAGING - PERSISTENT GENERALIZED LYMPHADENOPATHY";
	public static final String DERMATITIS = "DERMATITIS";
	public static final String HERPES_ZOSTER = "HERPES ZOSTER";
	public static final String HIV_STAGING_HSV_STOMATITIS = "	HIV STAGING - HSV STOMATITIS";
	public static final String HIV_STAGING_RECURRENT_UPPER_RESPIRATORY_INFECTION = "HIV STAGING - RECURRENT UPPER RESPIRATORY INFECTION";
	public static final String HIV_STAGING_STEROID_RESISTANT_THROMBOCYTOPENIA = "HIV STAGING - STEROID RESISTANT THROMBOCYTOPENIA";
	public static final String HUMAN_PAPILLOMAVIRUS = "HUMAN PAPILLOMAVIRUS";
	public static final String MOLLUSCUM_CONTAGIOSUM = "MOLLUSCUM CONTAGIOSUM";
	public static final String PAROTID_ENLARGEMENT = "PAROTID ENLARGEMENT";
	public static final String VERRUCA_PLANUS = "VERRUCA PLANUS";
	public static final String RECURRENT_ORAL_ULCERATION = "RECURRENT ORAL ULCERATION";
	public static final String PAPULAR_PRURITIC_ERUPTION = "PAPULAR PRURITIC ERUPTION";
	public static final String FUNGAL_NAIL_INFECTIONS = "FUNGAL NAIL INFECTIONS";
	public static final String LINEAR_GINGIVAL_ERYTHEMA = "LINEAR GINGIVAL ERYTHEMA";
	public static final String WARTS_GENITAL = "WARTS, GENITAL";
	public static final String CHRONIC_UPPER_RESPIRATORY_TRACT_INFECTIONS = "CHRONIC UPPER RESPIRATORY TRACT INFECTIONS";
	public static final String HEPATOSPLENOMEGALY = "HEPATOSPLENOMEGALY";
	public static final String DIARRHEA_CHRONIC = "DIARRHEA, CHRONIC";
	public static final String FAILURE_TO_THRIVE = "FAILURE TO THRIVE";
	public static final String HIV_STAGING_CANDIDIASIS_ORORESPIRATORY_TRACT = "HIV STAGING - CANDIDIASIS, ORORESPIRATORY TRACT";
	public static final String HIV_STAGING_LYMPHOID_INTERSTITIAL_PNEUMONIA = "HIV STAGING - LYMPHOID INTERSTITIAL PNEUMONIA";
	public static final String HIV_STAGING_PEDS_HERPES_ZOSTER = "HIV STAGING - PEDS HERPES ZOSTER";
	public static final String HIV_STAGING_RECURRENT_BACTERIAL_PNEUMONIA = "HIV STAGING - RECURRENT BACTERIAL PNEUMONIA";
	public static final String HIV_STAGING_REFRACTORY_ANEMIA = "HIV STAGING - REFRACTORY ANEMIA";
	public static final String HIV_STAGING_VARICELLA_DISSEMINATED = "HIV STAGING - VARICELLA, DISSEMINATED";
	public static final String PNEUMONIA_TUBERCULOUS = "PNEUMONIA, TUBERCULOUS";
	public static final String RECTOVAGINAL_FISTULA = "RECTOVAGINAL FISTULA";
	public static final String HIV_STAGING_MODERATE_MALNUTRITION = "HIV STAGING - MODERATE MALNUTRITION";
	public static final String HIV_STAGING_PERSISTENT_FEVER = "HIV STAGING - PERSISTENT FEVER";
	public static final String CANDIDIASIS_ORAL = "CANDIDIASIS, ORAL";
	public static final String ORAL_HAIRY_LEUKOPLAKIA = "ORAL HAIRY LEUKOPLAKIA";
	public static final String LYMPH_NODE_TUBERCULOSIS = "LYMPH NODE TUBERCULOSIS";
	public static final String HIV_STAGING_CHRONIC_HIV_ASSOCIATED_LUNG_DISEASE = "HIV STAGING - CHRONIC HIV-ASSOCIATED LUNG DISEASE";
	public static final String HIV_STAGING_UNEXAPLINED_ANEMIA_NEUTROPENIA = "HIV STAGING - UNEXAPLINED ANEMIA, NEUTROPENIA, OR CHRONIC THROMBOCYTOPENIA";
	public static final String HIV_STAGING_ACUTE_NECROTIZING_ULCERATIVE_GINGIVITIS_PERIODONTIS = "HIV STAGING - ACUTE NECROTIZING ULCERATIVE, GINGIVITIS, OR PERIODONTITIS";
	public static final String CANDIDIASIS = "CANDIDIASIS";
	public static final String CARDIOMYOPATHY = "CARDIOMYOPATHY";
	public static final String CRYPTOCOCCOSIS = "CRYPTOCOCCOSIS";
	public static final String ENCEPHALOPATHY = "ENCEPHALOPATHY";
	public static final String HIV_STAGING_COCCIDIODOMYCOSIS_DISSEMINATED = "HIV STAGING - COCCIDIODOMYCOSIS, DISSEMINATED";
	public static final String HIV_STAGING_CRYPTOCOCCOSIS_EXTRAPULMONARY = "HIV STAGING - CRYPTOCOCCOSIS, EXTRAPULMONARY";
	public static final String HIV_STAGING_CRYPTOSPORIDIOSIS = "HIV STAGING - CRYPTOSPORIDIOSIS";
	public static final String HIV_STAGING_CYTOMEGALOVIRUS_DISEASE = "HIV STAGING - CYTOMEGALOVIRUS DISEASE";
	public static final String HIV_STAGING_HISTOPLASMOSIS_DISSEMINATED = "HIV STAGING - HISTOPLASMOSIS, DISSEMINATED";
	public static final String HIV_STAGING_MYCOBACTERIUM_OTHER = "HIV STAGING - MYCOBACTERIUM, OTHER";
	public static final String HIV_STAGING_NONRESPONSIVE_HERPES_SIMPLEX_VIRUS = "HIV STAGING - NONRESPONSIVE HERPES SIMPLEX VIRUS";
	public static final String HIV_STAGING_SEVERE_BACTERIAL_INFECTION = "HIV STAGING - SEVERE BACTERIAL INFECTION";
	public static final String NEPHROPATHY = "NEPHROPATHY";
	public static final String PNEUMOCYSTIC_CARINII_PNEUMONIA = "PNEUMOCYSTIC CARINII PNEUMONIA";
	public static final String PROGRESSIVE_MULTIFOCAL_LEUKOENCEPHALOPATHY = "PROGRESSIVE MULTIFOCAL LEUKOENCEPHALOPATHY";
	public static final String TOXOPLASMOSIS = "TOXOPLASMOSIS";
	public static final String WASTING_SYNDROME = "WASTING SYNDROME";
	public static final String CANDIDIASIS_OESOPHAGEAL = "CANDIDIASIS, OESOPHAGEAL";
	public static final String MYCOBACTERIUM_TUBERCULOSIS_EXTRAPULMONARY = "MYCOBACTERIUM TUBERCULOSIS, EXTRAPULMONARY";
	public static final String HIV_STAGING_CHRONIC_ISOSPORIASIS = "HIV STAGING - CHRONIC ISOSPORIASIS";
	public static final String HIV_STAGING_CEREBRAL_B_CELL_NON_HODGKIN_LYMPHOMA = "HIV STAGING - CEREBRAL OR B-CELL NON-HODGKIN LYMPHOMA";
	//End of Additional Concepts for WHO Stage Rule
	
	//TRANSFER OUTSIDE AMPATH LOCATIONS
	public static final String NON_AMPATH = "NON-AMPATH";
	public static final String REASON_EXITED_CARE = "REASON EXITED CARE";
	public static final String PATIENT_TRANSFERRED_OUT = "PATIENT TRANSFERRED OUT";
	public static final String OUTCOME_AT_END_OF_TUBERCULOSIS_TREATMENT = "OUTCOME AT END OF TUBERCULOSIS TREATMENT";
	public static final String PRESUMPTIVE_HIV_STAGING_TUBERCULOSIS_PULMONARY = "PRESUMPTIVE HIV STAGING - TUBERCULOSIS, PULMONARY";
	public static final String OTITIS_MEDIA = "OTITIS MEDIA";
	
	//WHO staging questions start here
	public static final String ADULT_WHO_CONDITION_QUERY = "ADULT WHO CONDITION QUERY";
	public static final String PEDS_CDC_SPECIFIC_CONDITION_QUERY = "PEDS CDC SPECIFIC CONDITION QUERY";
	public static final String PED_SCDC_CATEGORY_QUERY = "PEDS CDC CATEGORY QUERY";
	public static final String PEDS_WHO_SPECIFIC_CONDITION_QUERY = "PEDS WHO SPECIFIC CONDITION QUERY";
	public static final String DAPSONE = "DAPSONE";

	// Age group for use in some rules
	public static enum AgeGroup {
		UNDER_EIGHTEEN_MONTHS,
		EIGHTEEN_MONTHS_TO_FIVE_YEARS,
		FIVE_YEARS_TO_TWELVE_YEARS,
		ABOVE_TWELVE_YEARS
	};

}
